import type { Facility } from '../types/facility';

/**
 * Hand-verified CDSS licence corrections, applied on top of
 * LICENSE_ENRICHMENT in locations.ts.
 *
 * WHY THIS FILE EXISTS
 *
 * scripts/import-cdss.mjs matches curated records to CCLD roster rows, and its
 * matcher produced false positives. `nameTokensOverlap` divides the token
 * intersection by `min(setSize)`, and STOPWORDS strips HOME / CARE / ELDERLY /
 * ASSISTED / LIVING / SENIOR. So:
 *
 *     "GROVE HOME CARE"                    -> {GROVE}                       size 1
 *     "Love and Serenity of Elk Grove III" -> {LOVE,SERENITY,ELK,GROVE,III}  size 5
 *     intersection 1 / min(1,5) = 1.0  >= 0.8 threshold, ZIPs match -> MATCH
 *
 * Any roster facility whose name reduces to a single token matches any curated
 * record in the same ZIP that happens to share it. Two records were assigned
 * another facility's licence number, and both wrong numbers happened to carry
 * a CURRENT status that masked an ON PROBATION licence at the real address.
 *
 * The corrections are hand-applied here rather than in imported.generated.ts
 * because that file is autogenerated and a hand edit there would be erased by
 * the next `node scripts/import-cdss.mjs` run.
 *
 * EVERY VALUE BELOW IS COPIED FROM assisted-living-sacramento-area.csv — the
 * CCLD roster export — matched on facility_number. No value is inferred.
 *
 * RETIRING THIS FILE
 *
 * Fix nameTokensOverlap (Jaccard + a minimum-token floor + reject any match
 * where names AND addresses both disagree), re-run the import, confirm the
 * generated LICENSE_ENRICHMENT reproduces these four rows, then delete this
 * file and its use in locations.ts. Do not delete it before that: without it
 * two facilities on probation display as verified-current.
 */
export const LICENSE_CORRECTIONS: Record<string, Partial<Facility>> = {
  /**
   * Was assigned #342700730 — ABOUNDING LOVE III at 5105 Village Wood Drive,
   * a different building, and the licence belonging to the `abounding-love-iii`
   * record below. Straight swap.
   *
   * CSV: 342700440,ABOUNDING LOVE HOME CARE,27 TRISTAN CIR,SACRAMENTO,95823,
   *      capacity 6,ON PROBATION,10/29/2018
   */
  'abounding-love-home-care': {
    license_number: '342700440',
    license_type: 'RCFE',
    license_status: 'on_probation',
    license_effective_date: '2018-10-29',
    capacity: 6,
    county: 'Sacramento',
  },

  /**
   * Was assigned #342700730 to nobody — this record had no licence at all,
   * because the row above consumed its roster entry.
   *
   * CSV: 342700730,ABOUNDING LOVE III,5105 VILLAGE WOOD DRIVE,SACRAMENTO,95823,
   *      capacity 6,LICENSED,12/10/2019
   */
  'abounding-love-iii': {
    license_number: '342700730',
    license_type: 'RCFE',
    license_status: 'current',
    license_effective_date: '2019-12-10',
    capacity: 6,
    county: 'Sacramento',
  },

  /**
   * Was assigned #342700018 — GROVE HOME CARE at 8410 Terracotta Circle,
   * Sacramento. Wrong facility, wrong city, and the licence date it printed
   * ("Licensed since February 22, 2017") belonged to that other home.
   *
   * CSV: 342700828,LOVE AND SERENITY OF ELK GROVE III,9442 MAZATLAN WAY,
   *      ELK GROVE,95624,capacity 6,LICENSED,8/3/2020
   */
  'love-and-serenity-iii-of-elk-grove': {
    license_number: '342700828',
    license_type: 'RCFE',
    license_status: 'current',
    license_effective_date: '2020-08-03',
    capacity: 6,
    county: 'Sacramento',
  },

  /**
   * Had no licence assigned at all, so it rendered the unverified-badge
   * fallback removed in the previous commit. Its real licence is on probation.
   *
   * CSV: 342700201,LOVE AND SERENITY OF ELK GROVE II,9279 ORANGE CREST COURT,
   *      ELK GROVE,95624,capacity 6,ON PROBATION,10/19/2017
   */
  'love-and-serenity-of-elk-grove-ii': {
    license_number: '342700201',
    license_type: 'RCFE',
    license_status: 'on_probation',
    license_effective_date: '2017-10-19',
    capacity: 6,
    county: 'Sacramento',
  },
};
