/**
 * Public locations API for the rest of the app.
 *
 * Two data sources merge here:
 *
 *   1. CURATED_FACILITIES — the original hand-maintained 24 records, with
 *      rich descriptions, photo sets, and partner flags. Edit in curated.ts.
 *
 *   2. IMPORTED_FACILITIES — license-verified RCFE records pulled from the
 *      CA Community Care Licensing roster. Autogenerated by
 *        node scripts/import-cdss.mjs
 *      Never hand-edit imported.generated.ts.
 *
 * LICENSE_ENRICHMENT layers CCLD license fields onto matched curated
 * records, leaving description/photos/care_types intact.
 */

import type { Facility } from '../types/facility';
import { CURATED_FACILITIES } from './curated';
import { IMPORTED_FACILITIES, LICENSE_ENRICHMENT } from './imported.generated';

const enrichedCurated: Facility[] = CURATED_FACILITIES.map((f) => {
  const extra = LICENSE_ENRICHMENT[f.id];
  return extra ? { ...f, ...extra } : f;
});

export const locations: Facility[] = [...enrichedCurated, ...IMPORTED_FACILITIES];

export const getAllLocations = (): Facility[] => locations;

export const getLocationById = (id: string): Facility | undefined =>
  locations.find(location => location.id === id);

export const getFeaturedLocations = (): Facility[] =>
  locations.filter(location => location.is_partner === true);

export const searchLocations = (query: string): Facility[] => {
  const q = query.toLowerCase();
  return locations.filter(location =>
    location.name.toLowerCase().includes(q) ||
    location.city.toLowerCase().includes(q) ||
    location.zip.includes(q)
  );
};

// Legacy alias kept so existing imports compile during the rollout.
export type LocationType = Facility;

export const getCareTypes = () => [
  { id: 'assisted-living', title: 'Assisted Living', description: 'For seniors who need some help with daily activities while maintaining their independence.', icon: 'users' },
  { id: 'memory-care', title: 'Memory Care', description: "Specialized care for seniors with Alzheimer's, dementia, or other memory conditions.", icon: 'brain' },
  { id: 'independent-living', title: 'Independent Living', description: 'For active seniors who want a maintenance-free lifestyle with amenities and social activities.', icon: 'home' },
  { id: 'skilled-nursing', title: 'Skilled Nursing', description: '24/7 medical care for seniors with complex health needs requiring professional nursing services.', icon: 'stethoscope' },
];
